apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: default
data:
  SPRING_APPLICATION_NAME: "gateway"
  SERVER_PORT: "9000"
  JWT_ISSUER_URI: "http://172.205.16.15/realms/kwetter"
  JWT_JWK_SET_URI: "http://172.205.16.15/realms/kwetter/protocol/openid-connect/certs"
  USER_SERVICE_URL: "http://user-service:9001"
  POST_SERVICE_URL: "http://post-service:9002"
  FOLLOW_SERVICE_URL: "http://follow-service:9003"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000"